
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hangman.java
 *
 * Created on 14 Feb, 2015, 10:08:12 PM
 */

/**
 *
 * @author R. Ganapathy
 */
public class Hangman extends javax.swing.JFrame {
    

    /** Creates new form Hangman */
    public Hangman() {
        initComponents();
        
           }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Guess = new javax.swing.JTextField();
        Tf2 = new javax.swing.JTextField();
        Tf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Tf3 = new javax.swing.JTextField();
        Tf4 = new javax.swing.JTextField();
        Tf5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        La = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ta1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Ta2 = new javax.swing.JTextArea();
        La1 = new javax.swing.JLabel();
        T1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        time = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(980, 520));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l1);
        l1.setBounds(110, 350, 220, 30);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang5.PNG"))); // NOI18N
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l2);
        l2.setBounds(310, 90, 10, 260);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        l3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l3);
        l3.setBounds(90, 80, 230, 20);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        l4.setText("jLabel5");
        l4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l4);
        l4.setBounds(180, 100, 20, 16);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang1.PNG"))); // NOI18N
        l5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l5);
        l5.setBounds(140, 110, 110, 100);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang5.PNG"))); // NOI18N
        l6.setText("jLabel7");
        l6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(l6);
        l6.setBounds(190, 210, 10, 120);

        l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        l7.setText("jLabel8");
        jPanel1.add(l7);
        l7.setBounds(100, 240, 90, 10);

        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        jPanel1.add(l8);
        l8.setBounds(200, 240, 90, 10);

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        jPanel1.add(l9);
        l9.setBounds(100, 280, 90, 10);

        l10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hang6.PNG"))); // NOI18N
        jPanel1.add(l10);
        l10.setBounds(200, 280, 90, 10);
        jPanel1.add(Label1);
        Label1.setBounds(4, 10, 370, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(530, 30, 370, 410);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("HANGMAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 200, 40);

        Guess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                GuessMouseReleased(evt);
            }
        });
        Guess.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GuessKeyReleased(evt);
            }
        });
        getContentPane().add(Guess);
        Guess.setBounds(60, 260, 90, 30);

        Tf2.setMinimumSize(new java.awt.Dimension(16, 20));
        Tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(Tf2);
        Tf2.setBounds(110, 350, 70, 30);

        Tf1.setMinimumSize(new java.awt.Dimension(16, 20));
        Tf1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Tf1MouseReleased(evt);
            }
        });
        Tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf1ActionPerformed(evt);
            }
        });
        Tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tf1KeyPressed(evt);
            }
        });
        getContentPane().add(Tf1);
        Tf1.setBounds(20, 350, 70, 30);

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 204));
        jLabel12.setText("Your Guess");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 190, 90, 50);

        Tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(Tf3);
        Tf3.setBounds(190, 350, 60, 30);

        Tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(Tf4);
        Tf4.setBounds(260, 350, 70, 30);

        Tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(Tf5);
        Tf5.setBounds(340, 350, 70, 30);

        jButton4.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jButton4.setText("Give me a word");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(40, 420, 150, 30);
        getContentPane().add(La);
        La.setBounds(200, 190, 60, 30);

        jButton1.setText("Back");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 420, 90, 30);

        Ta1.setColumns(20);
        Ta1.setRows(5);
        Ta1.setBorder(javax.swing.BorderFactory.createTitledBorder("CORRECT WORDS"));
        jScrollPane2.setViewportView(Ta1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(250, 220, 180, 110);

        jButton2.setFont(new java.awt.Font("Andalus", 0, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 420, 80, 30);

        Ta2.setColumns(20);
        Ta2.setRows(5);
        Ta2.setBorder(javax.swing.BorderFactory.createTitledBorder("WRONG WORDS"));
        jScrollPane3.setViewportView(Ta2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(250, 80, 178, 110);

        La1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(La1);
        La1.setBounds(440, 350, 50, 40);
        getContentPane().add(T1);
        T1.setBounds(400, 20, 80, 30);

        jButton3.setText("Add score");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 420, 90, 30);

        jLabel3.setBackground(new java.awt.Color(0, 153, 51));
        jLabel3.setFont(new java.awt.Font("French Script MT", 1, 36)); // NOI18N
        jLabel3.setText("<html>\nThis is Hangman .....\n<br>\nWe will give you a word when you click on the\n<br>\nGive me a word button. Once you click this the timer starts.\n<br>\nyou need to guess the word by entering each letter of the \n<br>\nword one at a time .If the letter is correct it will be displayed\n<br>\nin its position , if it is not then the man will be hanged one by one.\n</html>\n");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 940, 540);

        time.setColumns(20);
        time.setRows(5);
        jScrollPane1.setViewportView(time);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 90, 80, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HangMan 2.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-50, 0, 980, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int n,len,count,score,t;
String aa,ab,ac,ad,ae,str,s;
String[]hang={
"STORE",
"SHIRT",
"CLOCK",
"PANTS",
"DATES",
"SKIRT",
"MODEL",
"MONEY",
"MONKS",
"TONGS",
"WORLD",
"DRAPE",
"WATCH",
"MATCH",
"CATCH",
"BADGE",
"DEBUG",
"LIGHT",
"SOUND",
"FRAME",
"LAPSE",
"PLACE",
"CRAMP",
"CRUSH",
"JUICE",
"BIKES",
"RIDGE",
"GRIEF",
"ALERT",
"REIGN",
"CATER",
"DIRGE",
"BOGEY",
"BONUS",
"DANCE",
"MUSIC",
"BOGUS",
"BRACE",
"GAUDY",
"GAUNT",
"POWER",
"MOWER",
"NURSE",
"HALVE",
"FLAKE",
"ORBIT",
"PHONE",
"ORGAN",
"SUPER",
"OVERT",
"OXIDE",
"PROVE",
"PROWL",
"PROXY",
"PULSE",
"SHANK",
"SHADY",
"SMILE",
"MILES",
"SNARL",
"SNACK",
"SNIPE",
"PRIZE",
"WRITE",
"GUARD",
"TRAIL",
"TRAGIC",
"TRAMP",
"TOWER",
"GUEST",
"GUILD",
"BUILD",
"BUILT",
"GRUNT",
"BRUNT",
"FORCE",
"ROUTE",
"FORGE",
"CROWD",
"SPINE",
"THORN",
"CRASH",
"HARSH",
"CRUEL",
"LOTUS",
"CRYPT",
"WORST",
"CURVE",
"TOPIC",
"SHIFT",
"TOXIC",
"TRIBE",
"TRICK",
"DRIVE",
"PEACE",
"GRAND",
"TEACH",
"COURT",
"WIRES",
"CASTE"
};
 final Timer timer=new Timer();
  TimerTask task =new TimerTask()
                {
                   int ti = 0;
                    public void run()
                {
                    ti++;
                    time.setText(""+ti);                                 
                }
                };
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
timer.scheduleAtFixedRate(task, 1000, 1000);
int lower=1,upper=100;
Random rn =new Random();
n=rn.nextInt(lower+(int)(Math.random()*((upper-lower)+1)));
Guess.requestFocus();
System.out.println(n);// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
 l1.setVisible(false);
 l2.setVisible(false);
 l3.setVisible(false);
 l4.setVisible(false);
 l5.setVisible(false);
 l6.setVisible(false);
 l7.setVisible(false);
 l8.setVisible(false);
 l9.setVisible(false);
 l10.setVisible(false);
 Guess.requestFocus();
 Ta1.setVisible(false);
 Ta1.setVisible(false);
 Tf1.setVisible(false);
 Tf2.setVisible(false);
 Tf3.setVisible(false);
 Tf4.setVisible(false);
 Guess.setVisible(false);
 T1.setVisible(false);
 jLabel1.setVisible(false);
 jButton1.setVisible(false);
 jButton1.setVisible(false);
 jButton1.setVisible(false);
 jButton1.setVisible(false);
 La1.setVisible(false);
 jLabel12.setVisible(false);
time.setVisible(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Recreation Obj= new Recreation();
        Obj.setVisible(true);
        Hangman.this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Tf1.setText("");
Tf2.setText("");
Tf3.setText("");
Tf4.setText("");
Tf5.setText("");
Guess.setText("");
Ta1.setText("");
Ta2.setText("");
 l1.setVisible(false);
 l2.setVisible(false);
 l3.setVisible(false);
 l4.setVisible(false);
 l5.setVisible(false);
 l6.setVisible(false);
 l7.setVisible(false);
 l8.setVisible(false);
 l9.setVisible(false);
 l10.setVisible(false);
 count=0;
 T1.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Tf1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf1KeyPressed

    private void Tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tf1ActionPerformed

    private void Tf1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tf1MouseReleased
// TODO add your handling code here:
    }//GEN-LAST:event_Tf1MouseReleased

    private void Tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf2ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Tf2ActionPerformed

    private void Tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf3ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_Tf3ActionPerformed

    private void Tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf4ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Tf4ActionPerformed

    private void Tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tf5ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_Tf5ActionPerformed

    private void GuessMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuessMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_GuessMouseReleased

    private void GuessKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GuessKeyReleased
len=hang.length;
String gue=Guess.getText();
String word=hang[n];
String haha=word.substring(0, 5);
String a=word.charAt(0)+"";
String b=word.charAt(1)+"";
String c=word.charAt(2)+"";
String d=word.charAt(3)+"";
String e=word.charAt(4)+"";
if(gue.equals(a))
{
Tf1.setText(gue);
Ta1.append(gue+'\n');
        
}
else if(gue.equals(b))
  {
Tf2.setText(gue);
Ta1.append(gue+'\n');
  }
else if(gue.equals(c))
    {
Tf3.setText(gue);
Ta1.append(gue+'\n');
    }
else if(gue.equals(d))
    {
Tf4.setText(gue);
Ta1.append(gue+'\n');
    }
else if(gue.equals(e))
    {
Tf5.setText(gue);
Ta1.append(gue+'\n');
    }
else
   count++;
switch(count)
{
    case 1:
     l1.setVisible(true);
     break;
    case 2:
     l2.setVisible(true);
     break;
    case 3:
     l3.setVisible(true);
         break;
    case 4:
     l4.setVisible(true);
         break;       
    case 5:
     l5.setVisible(true);
         break;
    case 6:
     l6.setVisible(true);
         break;
    case 7:
     l7.setVisible(true);
         break;
    case 8:
     l8.setVisible(true);
         break;
    case 9:
     l9.setVisible(true);
         break;
     case 10:
     l10.setVisible(true);
         break;
     case 11:
         timer.cancel();
      JOptionPane.showMessageDialog(null,"The word is "+word);     
         score=0;
          La1.setText(" "+score);
        
  }
Ta2.append(gue+'\n');
Guess.requestFocus();
Guess.setText("");
        
aa=Tf1.getText();
ab=Tf2.getText();
ac=Tf3.getText();
ad=Tf4.getText();
ae=Tf5.getText();
if((aa.equals(a))&&(ab.equals(b))&&(ac.equals(c))&&(ad.equals(d))&&(ae.equals(e))){
   timer.cancel();
    JOptionPane.showMessageDialog(null, "You Have Won"); 
    score=10;
    La1.setText(""+score);
    if(haha.equals("A"))
        Label1.setIcon(new ImageIcon("C:\\Project\\src\\coupons.PNG"));
}
     /*final Timer timer=new Timer();
  TimerTask task =new TimerTask()
                {
                    int ti = 0;
                    public void run()
                {
                    ti++;
                    System.out.println(ti);
                   
                    
timer.cancel();
                }
                };
        timer.scheduleAtFixedRate(task, 1000, 1000);*/
       
        
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_GuessKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
str=time.getText();
t=Integer.parseInt(str);
s=T1.getText();
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/IpProject", "root", "aghs123");
    Statement st=con.createStatement();
    String q="Insert into Hangman values("+"'"+s+"'"+","+t+","+"0"+");";
    String h="Select Highscore from hangman ;";
  st.executeUpdate(q);
    ResultSet rs=st.executeQuery(h);
    while(rs.next())
    {
        
       int  a= rs.getInt("Highscore"); 
       
        if(t>a)
        {  
            JOptionPane.showMessageDialog(null,"New High score!!");
        String d="Update Hangman set(Highscore = "+t+") where username like "+s+";";
        
        st.executeUpdate(d);
        }
    }
    
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Guess;
    private javax.swing.JLabel La;
    private javax.swing.JLabel La1;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextArea Ta1;
    private javax.swing.JTextArea Ta2;
    private javax.swing.JTextField Tf1;
    private javax.swing.JTextField Tf2;
    private javax.swing.JTextField Tf3;
    private javax.swing.JTextField Tf4;
    private javax.swing.JTextField Tf5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JTextArea time;
    // End of variables declaration//GEN-END:variables

    private void ti() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
