

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Minesweeper.java
 *
 * Created on 8 Feb, 2015, 9:57:46 PM
 */

/**
 *
 * @author R. Ganapathy
 */
public class Minesweeper extends javax.swing.JFrame {      

   
class game{
    void disp(){
 B3.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B6.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B84.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B79.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B60.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B49.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B37.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B122.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B14.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B55.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B43.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B18.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B39.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B65.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B33.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B29.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B63.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B75.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B9.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B86.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B81.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B95.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B100.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B136.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B116.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B138.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B144.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B127.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B73.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B104.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B88.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B132.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B41.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B106.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B111.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"))  ;
 B140.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
 B119.setIcon(new ImageIcon("D:\\Project\\src\\Mines1.PNG"));
  JOptionPane.showMessageDialog(null,"You lose");
 L1.setText("your Score is "+count);
 
    }
   }
    /** Creates new form Minesweeper */
    public Minesweeper() {
     initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B13 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        B10 = new javax.swing.JButton();
        B11 = new javax.swing.JButton();
        B12 = new javax.swing.JButton();
        B24 = new javax.swing.JButton();
        B36 = new javax.swing.JButton();
        B48 = new javax.swing.JButton();
        B60 = new javax.swing.JButton();
        B72 = new javax.swing.JButton();
        B84 = new javax.swing.JButton();
        B96 = new javax.swing.JButton();
        B108 = new javax.swing.JButton();
        B120 = new javax.swing.JButton();
        B132 = new javax.swing.JButton();
        B144 = new javax.swing.JButton();
        B143 = new javax.swing.JButton();
        B142 = new javax.swing.JButton();
        B141 = new javax.swing.JButton();
        B140 = new javax.swing.JButton();
        B137 = new javax.swing.JButton();
        B136 = new javax.swing.JButton();
        B135 = new javax.swing.JButton();
        B134 = new javax.swing.JButton();
        B133 = new javax.swing.JButton();
        B131 = new javax.swing.JButton();
        B119 = new javax.swing.JButton();
        B107 = new javax.swing.JButton();
        B95 = new javax.swing.JButton();
        B83 = new javax.swing.JButton();
        B71 = new javax.swing.JButton();
        B59 = new javax.swing.JButton();
        B139 = new javax.swing.JButton();
        B35 = new javax.swing.JButton();
        B23 = new javax.swing.JButton();
        B130 = new javax.swing.JButton();
        B118 = new javax.swing.JButton();
        B106 = new javax.swing.JButton();
        B94 = new javax.swing.JButton();
        B82 = new javax.swing.JButton();
        B70 = new javax.swing.JButton();
        B58 = new javax.swing.JButton();
        B46 = new javax.swing.JButton();
        B34 = new javax.swing.JButton();
        B22 = new javax.swing.JButton();
        B129 = new javax.swing.JButton();
        B117 = new javax.swing.JButton();
        B105 = new javax.swing.JButton();
        B93 = new javax.swing.JButton();
        B81 = new javax.swing.JButton();
        B69 = new javax.swing.JButton();
        B138 = new javax.swing.JButton();
        B45 = new javax.swing.JButton();
        B33 = new javax.swing.JButton();
        B21 = new javax.swing.JButton();
        B128 = new javax.swing.JButton();
        B116 = new javax.swing.JButton();
        B104 = new javax.swing.JButton();
        B92 = new javax.swing.JButton();
        B80 = new javax.swing.JButton();
        B68 = new javax.swing.JButton();
        B122 = new javax.swing.JButton();
        B44 = new javax.swing.JButton();
        B32 = new javax.swing.JButton();
        B20 = new javax.swing.JButton();
        B127 = new javax.swing.JButton();
        B47 = new javax.swing.JButton();
        B103 = new javax.swing.JButton();
        B91 = new javax.swing.JButton();
        B79 = new javax.swing.JButton();
        B67 = new javax.swing.JButton();
        B55 = new javax.swing.JButton();
        B43 = new javax.swing.JButton();
        B31 = new javax.swing.JButton();
        B19 = new javax.swing.JButton();
        B126 = new javax.swing.JButton();
        B125 = new javax.swing.JButton();
        B124 = new javax.swing.JButton();
        B123 = new javax.swing.JButton();
        B56 = new javax.swing.JButton();
        B121 = new javax.swing.JButton();
        B114 = new javax.swing.JButton();
        B113 = new javax.swing.JButton();
        B57 = new javax.swing.JButton();
        B110 = new javax.swing.JButton();
        B109 = new javax.swing.JButton();
        B102 = new javax.swing.JButton();
        B101 = new javax.swing.JButton();
        B100 = new javax.swing.JButton();
        B99 = new javax.swing.JButton();
        B98 = new javax.swing.JButton();
        B97 = new javax.swing.JButton();
        B90 = new javax.swing.JButton();
        B89 = new javax.swing.JButton();
        B88 = new javax.swing.JButton();
        B87 = new javax.swing.JButton();
        B86 = new javax.swing.JButton();
        B115 = new javax.swing.JButton();
        B85 = new javax.swing.JButton();
        B112 = new javax.swing.JButton();
        B76 = new javax.swing.JButton();
        B75 = new javax.swing.JButton();
        B74 = new javax.swing.JButton();
        B73 = new javax.swing.JButton();
        B61 = new javax.swing.JButton();
        B62 = new javax.swing.JButton();
        B63 = new javax.swing.JButton();
        B64 = new javax.swing.JButton();
        B65 = new javax.swing.JButton();
        B66 = new javax.swing.JButton();
        B54 = new javax.swing.JButton();
        B111 = new javax.swing.JButton();
        B53 = new javax.swing.JButton();
        B78 = new javax.swing.JButton();
        B50 = new javax.swing.JButton();
        B49 = new javax.swing.JButton();
        B42 = new javax.swing.JButton();
        B41 = new javax.swing.JButton();
        B40 = new javax.swing.JButton();
        B39 = new javax.swing.JButton();
        B38 = new javax.swing.JButton();
        B37 = new javax.swing.JButton();
        B30 = new javax.swing.JButton();
        B29 = new javax.swing.JButton();
        B28 = new javax.swing.JButton();
        B27 = new javax.swing.JButton();
        B77 = new javax.swing.JButton();
        B25 = new javax.swing.JButton();
        B52 = new javax.swing.JButton();
        B14 = new javax.swing.JButton();
        B15 = new javax.swing.JButton();
        B16 = new javax.swing.JButton();
        B17 = new javax.swing.JButton();
        B18 = new javax.swing.JButton();
        B51 = new javax.swing.JButton();
        B26 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        L1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ta1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        T1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 590));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setText("MINESWEEPER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 30, 170, 50);
        getContentPane().add(B13);
        B13.setBounds(30, 140, 40, 30);

        B1.setToolTipText("");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(30, 110, 40, 30);

        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2);
        B2.setBounds(70, 110, 40, 30);

        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        getContentPane().add(B3);
        B3.setBounds(110, 110, 40, 30);

        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        getContentPane().add(B4);
        B4.setBounds(150, 110, 40, 30);

        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        getContentPane().add(B5);
        B5.setBounds(190, 110, 40, 30);

        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        getContentPane().add(B6);
        B6.setBounds(230, 110, 40, 30);

        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        getContentPane().add(B7);
        B7.setBounds(270, 110, 40, 30);

        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        getContentPane().add(B8);
        B8.setBounds(310, 110, 40, 30);

        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        getContentPane().add(B9);
        B9.setBounds(350, 110, 40, 30);
        getContentPane().add(B10);
        B10.setBounds(390, 110, 40, 30);

        B11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B11ActionPerformed(evt);
            }
        });
        getContentPane().add(B11);
        B11.setBounds(430, 110, 40, 30);
        getContentPane().add(B12);
        B12.setBounds(470, 110, 40, 30);
        getContentPane().add(B24);
        B24.setBounds(470, 140, 40, 30);
        getContentPane().add(B36);
        B36.setBounds(470, 170, 40, 30);

        B48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B48ActionPerformed(evt);
            }
        });
        getContentPane().add(B48);
        B48.setBounds(470, 200, 40, 30);

        B60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B60ActionPerformed(evt);
            }
        });
        getContentPane().add(B60);
        B60.setBounds(470, 230, 40, 30);

        B72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B72ActionPerformed(evt);
            }
        });
        getContentPane().add(B72);
        B72.setBounds(470, 260, 40, 30);

        B84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B84ActionPerformed(evt);
            }
        });
        getContentPane().add(B84);
        B84.setBounds(470, 290, 40, 30);

        B96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B96ActionPerformed(evt);
            }
        });
        getContentPane().add(B96);
        B96.setBounds(470, 320, 40, 30);
        getContentPane().add(B108);
        B108.setBounds(470, 350, 40, 30);

        B120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B120ActionPerformed(evt);
            }
        });
        getContentPane().add(B120);
        B120.setBounds(470, 380, 40, 30);

        B132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B132ActionPerformed(evt);
            }
        });
        getContentPane().add(B132);
        B132.setBounds(470, 410, 40, 30);

        B144.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B144ActionPerformed(evt);
            }
        });
        getContentPane().add(B144);
        B144.setBounds(470, 440, 40, 30);
        getContentPane().add(B143);
        B143.setBounds(430, 440, 40, 30);

        B142.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B142ActionPerformed(evt);
            }
        });
        getContentPane().add(B142);
        B142.setBounds(390, 440, 40, 30);

        B141.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B141ActionPerformed(evt);
            }
        });
        getContentPane().add(B141);
        B141.setBounds(350, 440, 40, 30);

        B140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B140ActionPerformed(evt);
            }
        });
        getContentPane().add(B140);
        B140.setBounds(310, 440, 40, 30);

        B137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B137ActionPerformed(evt);
            }
        });
        getContentPane().add(B137);
        B137.setBounds(190, 440, 40, 30);

        B136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B136ActionPerformed(evt);
            }
        });
        getContentPane().add(B136);
        B136.setBounds(150, 440, 40, 30);

        B135.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B135ActionPerformed(evt);
            }
        });
        getContentPane().add(B135);
        B135.setBounds(110, 440, 40, 30);
        getContentPane().add(B134);
        B134.setBounds(70, 440, 40, 30);

        B133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B133ActionPerformed(evt);
            }
        });
        getContentPane().add(B133);
        B133.setBounds(30, 440, 40, 30);

        B131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B131ActionPerformed(evt);
            }
        });
        getContentPane().add(B131);
        B131.setBounds(430, 410, 40, 30);

        B119.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B119ActionPerformed(evt);
            }
        });
        getContentPane().add(B119);
        B119.setBounds(430, 380, 40, 30);

        B107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B107ActionPerformed(evt);
            }
        });
        getContentPane().add(B107);
        B107.setBounds(430, 350, 40, 30);

        B95.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B95ActionPerformed(evt);
            }
        });
        getContentPane().add(B95);
        B95.setBounds(430, 320, 40, 30);
        getContentPane().add(B83);
        B83.setBounds(430, 290, 40, 30);
        getContentPane().add(B71);
        B71.setBounds(430, 260, 40, 30);
        getContentPane().add(B59);
        B59.setBounds(430, 230, 40, 30);

        B139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B139ActionPerformed(evt);
            }
        });
        getContentPane().add(B139);
        B139.setBounds(270, 440, 40, 30);

        B35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B35ActionPerformed(evt);
            }
        });
        getContentPane().add(B35);
        B35.setBounds(430, 170, 40, 30);
        getContentPane().add(B23);
        B23.setBounds(430, 140, 40, 30);
        getContentPane().add(B130);
        B130.setBounds(390, 410, 40, 30);
        getContentPane().add(B118);
        B118.setBounds(390, 380, 40, 30);

        B106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B106ActionPerformed(evt);
            }
        });
        getContentPane().add(B106);
        B106.setBounds(390, 350, 40, 30);
        getContentPane().add(B94);
        B94.setBounds(390, 320, 40, 30);

        B82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B82ActionPerformed(evt);
            }
        });
        getContentPane().add(B82);
        B82.setBounds(390, 290, 40, 30);
        getContentPane().add(B70);
        B70.setBounds(390, 260, 40, 30);
        getContentPane().add(B58);
        B58.setBounds(390, 230, 40, 30);

        B46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B46ActionPerformed(evt);
            }
        });
        getContentPane().add(B46);
        B46.setBounds(390, 200, 40, 30);

        B34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B34ActionPerformed(evt);
            }
        });
        getContentPane().add(B34);
        B34.setBounds(390, 170, 40, 30);

        B22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B22ActionPerformed(evt);
            }
        });
        getContentPane().add(B22);
        B22.setBounds(390, 140, 40, 30);

        B129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B129ActionPerformed(evt);
            }
        });
        getContentPane().add(B129);
        B129.setBounds(350, 410, 40, 30);
        getContentPane().add(B117);
        B117.setBounds(350, 380, 40, 30);

        B105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B105ActionPerformed(evt);
            }
        });
        getContentPane().add(B105);
        B105.setBounds(350, 350, 40, 30);
        getContentPane().add(B93);
        B93.setBounds(350, 320, 40, 30);

        B81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B81ActionPerformed(evt);
            }
        });
        getContentPane().add(B81);
        B81.setBounds(350, 290, 40, 30);
        getContentPane().add(B69);
        B69.setBounds(350, 260, 40, 30);

        B138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B138ActionPerformed(evt);
            }
        });
        getContentPane().add(B138);
        B138.setBounds(230, 440, 40, 30);
        getContentPane().add(B45);
        B45.setBounds(350, 200, 40, 30);
        getContentPane().add(B33);
        B33.setBounds(350, 170, 40, 30);
        getContentPane().add(B21);
        B21.setBounds(350, 140, 40, 30);

        B128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B128ActionPerformed(evt);
            }
        });
        getContentPane().add(B128);
        B128.setBounds(310, 410, 40, 30);

        B116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B116ActionPerformed(evt);
            }
        });
        getContentPane().add(B116);
        B116.setBounds(310, 380, 40, 30);
        getContentPane().add(B104);
        B104.setBounds(310, 350, 40, 30);

        B92.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B92ActionPerformed(evt);
            }
        });
        getContentPane().add(B92);
        B92.setBounds(310, 320, 40, 30);
        getContentPane().add(B80);
        B80.setBounds(310, 290, 40, 30);
        getContentPane().add(B68);
        B68.setBounds(310, 260, 40, 30);

        B122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B122ActionPerformed(evt);
            }
        });
        getContentPane().add(B122);
        B122.setBounds(70, 410, 40, 30);

        B44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B44ActionPerformed(evt);
            }
        });
        getContentPane().add(B44);
        B44.setBounds(310, 200, 40, 30);
        getContentPane().add(B32);
        B32.setBounds(310, 170, 40, 30);

        B20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20ActionPerformed(evt);
            }
        });
        getContentPane().add(B20);
        B20.setBounds(310, 140, 40, 30);

        B127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B127ActionPerformed(evt);
            }
        });
        getContentPane().add(B127);
        B127.setBounds(270, 410, 40, 30);
        getContentPane().add(B47);
        B47.setBounds(430, 200, 40, 30);
        getContentPane().add(B103);
        B103.setBounds(270, 350, 40, 30);
        getContentPane().add(B91);
        B91.setBounds(270, 320, 40, 30);

        B79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B79ActionPerformed(evt);
            }
        });
        getContentPane().add(B79);
        B79.setBounds(270, 290, 40, 30);

        B67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B67ActionPerformed(evt);
            }
        });
        getContentPane().add(B67);
        B67.setBounds(270, 260, 40, 30);

        B55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B55ActionPerformed(evt);
            }
        });
        getContentPane().add(B55);
        B55.setBounds(270, 230, 40, 30);

        B43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B43ActionPerformed(evt);
            }
        });
        getContentPane().add(B43);
        B43.setBounds(270, 200, 40, 30);

        B31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B31ActionPerformed(evt);
            }
        });
        getContentPane().add(B31);
        B31.setBounds(270, 170, 40, 30);
        getContentPane().add(B19);
        B19.setBounds(270, 140, 40, 30);
        getContentPane().add(B126);
        B126.setBounds(230, 410, 40, 30);

        B125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B125ActionPerformed(evt);
            }
        });
        getContentPane().add(B125);
        B125.setBounds(190, 410, 40, 30);

        B124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B124ActionPerformed(evt);
            }
        });
        getContentPane().add(B124);
        B124.setBounds(150, 410, 40, 30);
        getContentPane().add(B123);
        B123.setBounds(110, 410, 40, 30);

        B56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B56ActionPerformed(evt);
            }
        });
        getContentPane().add(B56);
        B56.setBounds(310, 230, 40, 30);

        B121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B121ActionPerformed(evt);
            }
        });
        getContentPane().add(B121);
        B121.setBounds(30, 410, 40, 30);

        B114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B114ActionPerformed(evt);
            }
        });
        getContentPane().add(B114);
        B114.setBounds(230, 380, 40, 30);
        getContentPane().add(B113);
        B113.setBounds(190, 380, 40, 30);

        B57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B57ActionPerformed(evt);
            }
        });
        getContentPane().add(B57);
        B57.setBounds(350, 230, 40, 30);
        getContentPane().add(B110);
        B110.setBounds(70, 380, 40, 30);

        B109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B109ActionPerformed(evt);
            }
        });
        getContentPane().add(B109);
        B109.setBounds(30, 380, 40, 30);
        getContentPane().add(B102);
        B102.setBounds(230, 350, 40, 30);

        B101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B101ActionPerformed(evt);
            }
        });
        getContentPane().add(B101);
        B101.setBounds(190, 350, 40, 30);

        B100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B100ActionPerformed(evt);
            }
        });
        getContentPane().add(B100);
        B100.setBounds(150, 350, 40, 30);
        getContentPane().add(B99);
        B99.setBounds(110, 350, 40, 30);

        B98.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B98ActionPerformed(evt);
            }
        });
        getContentPane().add(B98);
        B98.setBounds(70, 350, 40, 30);
        getContentPane().add(B97);
        B97.setBounds(30, 350, 40, 30);
        getContentPane().add(B90);
        B90.setBounds(230, 320, 40, 30);

        B89.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B89ActionPerformed(evt);
            }
        });
        getContentPane().add(B89);
        B89.setBounds(190, 320, 40, 30);

        B88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B88ActionPerformed(evt);
            }
        });
        getContentPane().add(B88);
        B88.setBounds(150, 320, 40, 30);

        B87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B87ActionPerformed(evt);
            }
        });
        getContentPane().add(B87);
        B87.setBounds(110, 320, 40, 30);

        B86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B86ActionPerformed(evt);
            }
        });
        getContentPane().add(B86);
        B86.setBounds(70, 320, 40, 30);
        getContentPane().add(B115);
        B115.setBounds(270, 380, 40, 30);

        B85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B85ActionPerformed(evt);
            }
        });
        getContentPane().add(B85);
        B85.setBounds(30, 320, 40, 30);

        B112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B112ActionPerformed(evt);
            }
        });
        getContentPane().add(B112);
        B112.setBounds(150, 380, 40, 30);

        B76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B76ActionPerformed(evt);
            }
        });
        getContentPane().add(B76);
        B76.setBounds(150, 290, 40, 30);

        B75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B75ActionPerformed(evt);
            }
        });
        getContentPane().add(B75);
        B75.setBounds(110, 290, 40, 30);
        getContentPane().add(B74);
        B74.setBounds(70, 290, 40, 30);

        B73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B73ActionPerformed(evt);
            }
        });
        getContentPane().add(B73);
        B73.setBounds(30, 290, 40, 30);
        getContentPane().add(B61);
        B61.setBounds(30, 260, 40, 30);
        getContentPane().add(B62);
        B62.setBounds(70, 260, 40, 30);

        B63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B63ActionPerformed(evt);
            }
        });
        getContentPane().add(B63);
        B63.setBounds(110, 260, 40, 30);

        B64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B64ActionPerformed(evt);
            }
        });
        getContentPane().add(B64);
        B64.setBounds(150, 260, 40, 30);

        B65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B65ActionPerformed(evt);
            }
        });
        getContentPane().add(B65);
        B65.setBounds(190, 260, 40, 30);
        getContentPane().add(B66);
        B66.setBounds(230, 260, 40, 30);

        B54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B54ActionPerformed(evt);
            }
        });
        getContentPane().add(B54);
        B54.setBounds(230, 230, 40, 30);

        B111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B111ActionPerformed(evt);
            }
        });
        getContentPane().add(B111);
        B111.setBounds(110, 380, 40, 30);
        getContentPane().add(B53);
        B53.setBounds(190, 230, 40, 30);

        B78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B78ActionPerformed(evt);
            }
        });
        getContentPane().add(B78);
        B78.setBounds(230, 290, 40, 30);
        getContentPane().add(B50);
        B50.setBounds(70, 230, 40, 30);

        B49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B49ActionPerformed(evt);
            }
        });
        getContentPane().add(B49);
        B49.setBounds(30, 230, 40, 30);

        B42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B42ActionPerformed(evt);
            }
        });
        getContentPane().add(B42);
        B42.setBounds(230, 200, 40, 30);

        B41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B41ActionPerformed(evt);
            }
        });
        getContentPane().add(B41);
        B41.setBounds(190, 200, 40, 30);

        B40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B40ActionPerformed(evt);
            }
        });
        getContentPane().add(B40);
        B40.setBounds(150, 200, 40, 30);

        B39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B39ActionPerformed(evt);
            }
        });
        getContentPane().add(B39);
        B39.setBounds(110, 200, 40, 30);

        B38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B38ActionPerformed(evt);
            }
        });
        getContentPane().add(B38);
        B38.setBounds(70, 200, 40, 30);

        B37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B37ActionPerformed(evt);
            }
        });
        getContentPane().add(B37);
        B37.setBounds(30, 200, 40, 30);

        B30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B30ActionPerformed(evt);
            }
        });
        getContentPane().add(B30);
        B30.setBounds(230, 170, 40, 30);

        B29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B29ActionPerformed(evt);
            }
        });
        getContentPane().add(B29);
        B29.setBounds(190, 170, 40, 30);

        B28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B28ActionPerformed(evt);
            }
        });
        getContentPane().add(B28);
        B28.setBounds(150, 170, 40, 30);
        getContentPane().add(B27);
        B27.setBounds(110, 170, 40, 30);
        getContentPane().add(B77);
        B77.setBounds(190, 290, 40, 30);
        getContentPane().add(B25);
        B25.setBounds(30, 170, 40, 30);

        B52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B52ActionPerformed(evt);
            }
        });
        getContentPane().add(B52);
        B52.setBounds(150, 230, 40, 30);

        B14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B14ActionPerformed(evt);
            }
        });
        getContentPane().add(B14);
        B14.setBounds(70, 140, 40, 30);

        B15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B15ActionPerformed(evt);
            }
        });
        getContentPane().add(B15);
        B15.setBounds(110, 140, 40, 30);
        getContentPane().add(B16);
        B16.setBounds(150, 140, 40, 30);

        B17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B17ActionPerformed(evt);
            }
        });
        getContentPane().add(B17);
        B17.setBounds(190, 140, 40, 30);

        B18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B18ActionPerformed(evt);
            }
        });
        getContentPane().add(B18);
        B18.setBounds(230, 140, 40, 30);

        B51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B51ActionPerformed(evt);
            }
        });
        getContentPane().add(B51);
        B51.setBounds(110, 230, 40, 30);

        B26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B26ActionPerformed(evt);
            }
        });
        getContentPane().add(B26);
        B26.setBounds(70, 170, 40, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back2.JPG"))); // NOI18N
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(530, 380, 170, 90);

        L1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(L1);
        L1.setBounds(550, 280, 120, 30);

        Ta1.setColumns(20);
        Ta1.setRows(5);
        jScrollPane1.setViewportView(Ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(590, 130, 50, 40);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(580, 330, 73, 23);

        T1.setText("Hariny");
        getContentPane().add(T1);
        T1.setBounds(519, 60, 190, 20);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(580, 200, 73, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Miness2.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-110, 0, 860, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int count,t;
String str,s;

    
    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
B1.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B4.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
 L1.setText("your Score is "+count);
  // TODO add your handling code here:
}//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
B1.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
B2.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
L1.setText("your Score is "+count);
       // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed

game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
 
        game obj=new game();
obj.disp();
L1.setText("your Score is "+count);// TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
 
        game obj=new game();
obj.disp();
L1.setText("your Score is "+count);// TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void B14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B14ActionPerformed
 
        game obj=new game();
obj.disp();
L1.setText("your Score is "+count);// TODO add your handling code here:
    }//GEN-LAST:event_B14ActionPerformed

    private void B18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B18ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is "+count);// TODO add your handling code here:
    }//GEN-LAST:event_B18ActionPerformed

    private void B29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B29ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B29ActionPerformed

    private void B41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B41ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B41ActionPerformed

    private void B39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B39ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B39ActionPerformed

    private void B37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B37ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B37ActionPerformed

    private void B49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B49ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B49ActionPerformed

    private void B43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B43ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B43ActionPerformed

    private void B55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B55ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B55ActionPerformed

    private void B60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B60ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B60ActionPerformed

    private void B63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B63ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B63ActionPerformed

    private void B65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B65ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B65ActionPerformed

    private void B73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B73ActionPerformed
 
game obj=new game();
obj.disp();  
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B73ActionPerformed

    private void B75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B75ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B75ActionPerformed

    private void B79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B79ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B79ActionPerformed

    private void B81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B81ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B81ActionPerformed

    private void B84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B84ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B84ActionPerformed

    private void B95ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B95ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B95ActionPerformed

    private void B86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B86ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B86ActionPerformed

    private void B88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B88ActionPerformed
 
game obj=new game();
obj.disp();  
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B88ActionPerformed

    private void B100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B100ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B100ActionPerformed

    private void B106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B106ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B106ActionPerformed

    private void B111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B111ActionPerformed
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B111ActionPerformed

    private void B116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B116ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B116ActionPerformed

    private void B119ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B119ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B119ActionPerformed

    private void B122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B122ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B122ActionPerformed

    private void B127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B127ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B127ActionPerformed

    private void B132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B132ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B132ActionPerformed

    private void B144ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B144ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B144ActionPerformed

    private void B140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B140ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B140ActionPerformed

    private void B138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B138ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B138ActionPerformed

    private void B136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B136ActionPerformed
 
game obj=new game();
obj.disp();
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B136ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
B1.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B4.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
 L1.setText("Tour Score is"+count);
       // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
B1.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B4.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B5.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
 count++;
 L1.setText("your Score is"+count);
         // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
B7.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
         count++; 
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
B8.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
       count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B11ActionPerformed
B11.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B22.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
    L1.setText("your Score is"+count);    // TODO add your handling code here:
    }//GEN-LAST:event_B11ActionPerformed

    private void B15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B15ActionPerformed
B15.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
     L1.setText("your Score is"+count);  // TODO add your handling code here:
    }//GEN-LAST:event_B15ActionPerformed

    private void B17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B17ActionPerformed
B17.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B28.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
   L1.setText("your Score is"+count); // TODO add your handling code here:
    }//GEN-LAST:event_B17ActionPerformed

    private void B20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20ActionPerformed
B20.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
   L1.setText("your Score is"+count);     // TODO add your handling code here:
    }//GEN-LAST:event_B20ActionPerformed

    private void B22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B22ActionPerformed
B22.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
   L1.setText("your Score is"+count);     // TODO add your handling code here:
    }//GEN-LAST:event_B22ActionPerformed

    private void B26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B26ActionPerformed
  B22.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B26.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B38.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B30.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B31.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
   L1.setText("your Score is"+count);    // TODO add your handling code here:
    }//GEN-LAST:event_B26ActionPerformed

    private void B28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B28ActionPerformed
B28.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B40.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
   L1.setText("your Score is"+count);    // TODO add your handling code here:
    }//GEN-LAST:event_B28ActionPerformed

    private void B30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B30ActionPerformed
B30.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
L1.setText("your Score is"+count);       // TODO add your handling code here:
    }//GEN-LAST:event_B30ActionPerformed

    private void B31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B31ActionPerformed
B31.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B30.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;
  L1.setText("your Score is"+count);      // TODO add your handling code here:
    }//GEN-LAST:event_B31ActionPerformed

    private void B34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B34ActionPerformed
B34.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
  L1.setText("your Score is"+count);     // TODO add your handling code here:
    }//GEN-LAST:event_B34ActionPerformed

    private void B35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B35ActionPerformed
B35.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B46.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B58.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
 count++;
  L1.setText("your Score is"+count);     // TODO add your handling code here:
    }//GEN-LAST:event_B35ActionPerformed

    private void B48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B48ActionPerformed
B48.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
 L1.setText("your Score is"+count);      // TODO add your handling code here:
    }//GEN-LAST:event_B48ActionPerformed

    private void B46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B46ActionPerformed
B46.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
  L1.setText("your Score is"+count);      // TODO add your handling code here:
    }//GEN-LAST:event_B46ActionPerformed

    private void B44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B44ActionPerformed

  B56.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B44.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
 count++;
    L1.setText("your Score is"+count);   // TODO add your handling code here:
    }//GEN-LAST:event_B44ActionPerformed

    private void B42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B42ActionPerformed
B42.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
count++;
   L1.setText("your Score is"+count);     // TODO add your handling code here:
    }//GEN-LAST:event_B42ActionPerformed

    private void B40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B40ActionPerformed

 B40.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B42.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
      count++;  
      L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B40ActionPerformed

    private void B38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B38ActionPerformed

  B38.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B40.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B42.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B44.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B46.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
count++;
   L1.setText("your Score is"+count);   // TODO add your handling code here:
    }//GEN-LAST:event_B38ActionPerformed

    private void B51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B51ActionPerformed

  B48.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B51.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
      count++; 
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B51ActionPerformed

    private void B52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B52ActionPerformed
 B52.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
      count++;
      L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B52ActionPerformed

    private void B54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B54ActionPerformed
 B54.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
       count++; 
       L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B54ActionPerformed

    private void B56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B56ActionPerformed

  B56.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
    count++; 
    L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B56ActionPerformed

    private void B57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B57ActionPerformed

 B57.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B64.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    count++;
    L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B57ActionPerformed

    private void B64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B64ActionPerformed

  B64.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
   count++; 
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B64ActionPerformed

    private void B67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B67ActionPerformed

  B64.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B67.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
     count++;
     L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B67ActionPerformed

    private void B72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B72ActionPerformed

 B72.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    count++; 
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B72ActionPerformed

    private void B82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B82ActionPerformed

  B82.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
     count++;
     L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B82ActionPerformed

    private void B78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B78ActionPerformed

   B78.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B82.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
     count++; 
     L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B78ActionPerformed

    private void B76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B76ActionPerformed

   B87.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B76.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
     count++;  // TODO add your handling code here:
    }//GEN-LAST:event_B76ActionPerformed

    private void B85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B85ActionPerformed

  B85.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
      count++;
      L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B85ActionPerformed

    private void B87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B87ActionPerformed

  B87.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B92.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
       count++;
       L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B87ActionPerformed

    private void B89ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B89ActionPerformed

  B89.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
   B101.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
   count++;
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B89ActionPerformed

    private void B92ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B92ActionPerformed

 B92.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    B105.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;   
   count++; 
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B92ActionPerformed

    private void B96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B96ActionPerformed
 B96.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    count++; 
    L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B96ActionPerformed

    private void B107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B107ActionPerformed

  B107.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  count++;   
  L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B107ActionPerformed

    private void B105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B105ActionPerformed

  B105.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
  L1.setText("your Score is"+count);    // TODO add your handling code here:
    }//GEN-LAST:event_B105ActionPerformed

    private void B101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B101ActionPerformed

  B101.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++; 
  L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B101ActionPerformed

    private void B98ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B98ActionPerformed

 B92.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B98.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
count++;    
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B98ActionPerformed

    private void B109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B109ActionPerformed
  B109.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
 count++;    
 L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B109ActionPerformed

    private void B112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B112ActionPerformed

  B101.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
   B112.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B114.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    B124.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
   count++;  
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B112ActionPerformed

    private void B114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B114ActionPerformed
  B101.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  B112.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B114.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
    count++;  
    L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B114ActionPerformed

    private void B120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B120ActionPerformed

  B120.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  count++;  
  L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B120ActionPerformed

    private void B121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B121ActionPerformed
B121.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  B120.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
   count++;  
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B121ActionPerformed

    private void B124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B124ActionPerformed

  B120.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B124.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B125.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B128.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
   count++;  
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B124ActionPerformed

    private void B125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B125ActionPerformed

 B125.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
   count++; 
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B125ActionPerformed

    private void B128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B128ActionPerformed

  B128.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B129.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
   count++; 
   L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B128ActionPerformed

    private void B129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B129ActionPerformed

  B128.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B129.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 count++;  
 L1.setText("your Score is"+count);    // TODO add your handling code here:
    }//GEN-LAST:event_B129ActionPerformed

    private void B131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B131ActionPerformed

 B131.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B133.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B135.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;  
  L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B131ActionPerformed

    private void B142ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B142ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B142ActionPerformed

    private void B141ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B141ActionPerformed

  B141.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B141ActionPerformed

    private void B139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B139ActionPerformed

  B139.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B139ActionPerformed

    private void B137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B137ActionPerformed
 B137.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B139.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B141.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B137ActionPerformed

    private void B135ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B135ActionPerformed

  B135.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
 B137.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B139.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"));
  B141.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B135ActionPerformed

    private void B133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B133ActionPerformed

  B133.setIcon(new ImageIcon("D:\\Project\\src\\Mines.PNG"))  ;
  count++;
L1.setText("your Score is"+count);// TODO add your handling code here:
    }//GEN-LAST:event_B133ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Recreation Obj= new Recreation();
        Obj.setVisible(true);
        Minesweeper.this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  str=Ta1.getText();
t=Integer.parseInt(str);
s=T1.getText();
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost/IpProject", "root", "aghs123");
    Statement st=con.createStatement();
    String q="Insert into Minesweeper values("+","+"'"+s+"'"+","+count+","+"0"+");";
    String h="Select Highscore from Minesweeper ;";
  st.executeUpdate(q);
    ResultSet rs=st.executeQuery(h);
    while(rs.next())
    {
        
       int  a= rs.getInt("score"); 
       
        if(t>a)
        {  
            JOptionPane.showMessageDialog(null,"New High score!!");
        String d="Update Minesweeper set(Highscore = "+t+") where username like "+s+";";
        
        st.executeUpdate(d);
        }
    }
    
}
catch(Exception e)
{
    System.out.println(e.getMessage());
}          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     Minesweeper Obj= new  Minesweeper();
        Obj.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minesweeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B10;
    private javax.swing.JButton B100;
    private javax.swing.JButton B101;
    private javax.swing.JButton B102;
    private javax.swing.JButton B103;
    private javax.swing.JButton B104;
    private javax.swing.JButton B105;
    private javax.swing.JButton B106;
    private javax.swing.JButton B107;
    private javax.swing.JButton B108;
    private javax.swing.JButton B109;
    private javax.swing.JButton B11;
    private javax.swing.JButton B110;
    private javax.swing.JButton B111;
    private javax.swing.JButton B112;
    private javax.swing.JButton B113;
    private javax.swing.JButton B114;
    private javax.swing.JButton B115;
    private javax.swing.JButton B116;
    private javax.swing.JButton B117;
    private javax.swing.JButton B118;
    private javax.swing.JButton B119;
    private javax.swing.JButton B12;
    private javax.swing.JButton B120;
    private javax.swing.JButton B121;
    private javax.swing.JButton B122;
    private javax.swing.JButton B123;
    private javax.swing.JButton B124;
    private javax.swing.JButton B125;
    private javax.swing.JButton B126;
    private javax.swing.JButton B127;
    private javax.swing.JButton B128;
    private javax.swing.JButton B129;
    private javax.swing.JButton B13;
    private javax.swing.JButton B130;
    private javax.swing.JButton B131;
    private javax.swing.JButton B132;
    private javax.swing.JButton B133;
    private javax.swing.JButton B134;
    private javax.swing.JButton B135;
    private javax.swing.JButton B136;
    private javax.swing.JButton B137;
    private javax.swing.JButton B138;
    private javax.swing.JButton B139;
    private javax.swing.JButton B14;
    private javax.swing.JButton B140;
    private javax.swing.JButton B141;
    private javax.swing.JButton B142;
    private javax.swing.JButton B143;
    private javax.swing.JButton B144;
    private javax.swing.JButton B15;
    private javax.swing.JButton B16;
    private javax.swing.JButton B17;
    private javax.swing.JButton B18;
    private javax.swing.JButton B19;
    private javax.swing.JButton B2;
    private javax.swing.JButton B20;
    private javax.swing.JButton B21;
    private javax.swing.JButton B22;
    private javax.swing.JButton B23;
    private javax.swing.JButton B24;
    private javax.swing.JButton B25;
    private javax.swing.JButton B26;
    private javax.swing.JButton B27;
    private javax.swing.JButton B28;
    private javax.swing.JButton B29;
    private javax.swing.JButton B3;
    private javax.swing.JButton B30;
    private javax.swing.JButton B31;
    private javax.swing.JButton B32;
    private javax.swing.JButton B33;
    private javax.swing.JButton B34;
    private javax.swing.JButton B35;
    private javax.swing.JButton B36;
    private javax.swing.JButton B37;
    private javax.swing.JButton B38;
    private javax.swing.JButton B39;
    private javax.swing.JButton B4;
    private javax.swing.JButton B40;
    private javax.swing.JButton B41;
    private javax.swing.JButton B42;
    private javax.swing.JButton B43;
    private javax.swing.JButton B44;
    private javax.swing.JButton B45;
    private javax.swing.JButton B46;
    private javax.swing.JButton B47;
    private javax.swing.JButton B48;
    private javax.swing.JButton B49;
    private javax.swing.JButton B5;
    private javax.swing.JButton B50;
    private javax.swing.JButton B51;
    private javax.swing.JButton B52;
    private javax.swing.JButton B53;
    private javax.swing.JButton B54;
    private javax.swing.JButton B55;
    private javax.swing.JButton B56;
    private javax.swing.JButton B57;
    private javax.swing.JButton B58;
    private javax.swing.JButton B59;
    private javax.swing.JButton B6;
    private javax.swing.JButton B60;
    private javax.swing.JButton B61;
    private javax.swing.JButton B62;
    private javax.swing.JButton B63;
    private javax.swing.JButton B64;
    private javax.swing.JButton B65;
    private javax.swing.JButton B66;
    private javax.swing.JButton B67;
    private javax.swing.JButton B68;
    private javax.swing.JButton B69;
    private javax.swing.JButton B7;
    private javax.swing.JButton B70;
    private javax.swing.JButton B71;
    private javax.swing.JButton B72;
    private javax.swing.JButton B73;
    private javax.swing.JButton B74;
    private javax.swing.JButton B75;
    private javax.swing.JButton B76;
    private javax.swing.JButton B77;
    private javax.swing.JButton B78;
    private javax.swing.JButton B79;
    private javax.swing.JButton B8;
    private javax.swing.JButton B80;
    private javax.swing.JButton B81;
    private javax.swing.JButton B82;
    private javax.swing.JButton B83;
    private javax.swing.JButton B84;
    private javax.swing.JButton B85;
    private javax.swing.JButton B86;
    private javax.swing.JButton B87;
    private javax.swing.JButton B88;
    private javax.swing.JButton B89;
    private javax.swing.JButton B9;
    private javax.swing.JButton B90;
    private javax.swing.JButton B91;
    private javax.swing.JButton B92;
    private javax.swing.JButton B93;
    private javax.swing.JButton B94;
    private javax.swing.JButton B95;
    private javax.swing.JButton B96;
    private javax.swing.JButton B97;
    private javax.swing.JButton B98;
    private javax.swing.JButton B99;
    private javax.swing.JLabel L1;
    private javax.swing.JTextField T1;
    private javax.swing.JTextArea Ta1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
