
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kumar
 */
public class NUMBER extends javax.swing.JFrame {

    /**
     * Creates new form NUMBER
     */
    public NUMBER() {
        initComponents();    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ll = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        l1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        ll.setBackground(new java.awt.Color(102, 0, 102));
        ll.setFont(new java.awt.Font("Pristina", 0, 24)); // NOI18N
        ll.setForeground(new java.awt.Color(153, 153, 255));
        ll.setText("<html><center>RULES</center><br> This is a game base on your luck. In this game the gamer has to guess the pregenerated number ranging from 0 to 100 in the text field privided and then click on the Check button to chech if the numbers match. The guessed numbers will be automaticall entered into a list box for the gamer to avoid repeptition. This game is not timed and will continue till the number is guessed or till the gamer gives up.     Have Fun!<center>Click to Start</center></html>");
        ll.setOpaque(true);
        ll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llMouseClicked(evt);
            }
        });
        getContentPane().add(ll);
        ll.setBounds(0, 0, 540, 370);

        a.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        a.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                aMouseMoved(evt);
            }
        });
        a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aFocusLost(evt);
            }
        });
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(249, 92, 87, 34);

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(249, 180, 99, 43);

        l1.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(l1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(72, 70, 86, 238);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(345, 275, 55, 23);

        jLabel2.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        jLabel2.setText("Number Game");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(114, 11, 204, 48);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int k= (int)(Math.random()*100);
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
              System.out.println(k);
              int b,c;
             b=Integer.parseInt (a.getText());
             c=k-b;
             
             {DefaultListModel dlm= (DefaultListModel)l1.getModel();
              dlm.addElement(a.getText());
              l1.setModel(dlm);
            }

                                    
             if(b==k){
                  
                 JOptionPane.showMessageDialog(null,"BINGO! You got it right!");
             
                         }
             else 
             if(c>=-5&&c<=5)
                  JOptionPane.showMessageDialog(null,"You are very very close!");
              else
                  if((c>5&&c<10)||(c<-5&&c>-10))
  JOptionPane.showMessageDialog(null,"You are very close!");
              else
                      if((c>=10&&c<=20)||(c<=-10&&c>=-20))
  JOptionPane.showMessageDialog(null,"You are close");
               else
                      if((c<=20&&c>=50)&&(c>=-20&&c<=-50))
                          JOptionPane.showMessageDialog(null,"You are little far away!");
              else
                                        JOptionPane.showMessageDialog(null,"You are Very Far away!");  }
             
             
             catch(Exception e) {
            System.out.print(e.getMessage());
       }
         

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
     a.setText("");  // TODO add your handling code here:
    }//GEN-LAST:event_aMouseClicked

    private void aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusLost
       // TODO add your handling code here:
    }//GEN-LAST:event_aFocusLost

    private void aMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_aMouseMoved

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Recreation Obj= new Recreation();
        Obj.setVisible(true);
        NUMBER.this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void llMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseClicked
ll.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_llMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NUMBER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NUMBER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NUMBER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NUMBER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NUMBER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList l1;
    private javax.swing.JLabel ll;
    // End of variables declaration//GEN-END:variables
}
