
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kumar
 */


public class Sudoku6_1 extends javax.swing.JFrame {

    
    public Sudoku6_1() {
        initComponents();
    }
Timer tt=new Timer();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uuu = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        i = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        l = new javax.swing.JTextField();
        f = new javax.swing.JTextField();
        m = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        o = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        q = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        v = new javax.swing.JTextField();
        u = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        k = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        a = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        yy = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 51, 255));
        setMinimumSize(new java.awt.Dimension(490, 440));
        getContentPane().setLayout(null);

        uuu.setBackground(new java.awt.Color(0, 153, 102));
        uuu.setFont(new java.awt.Font("Freestyle Script", 0, 34)); // NOI18N
        uuu.setForeground(new java.awt.Color(255, 153, 0));
        uuu.setText("<html><center>RULES</center>This Sudoku game involves a grid of 36 rectangles. The grid is divided into 6 blocks, each containing 6 rectangles. The rules of the game are simple: each of the 6 blocks has to contain all the numbers 1-6 within its squares. Each number can only appear once in a row, column or box. And lastly, be as fast as you can as this game is timed! <center>Click to start</center></html>");
        uuu.setMinimumSize(new java.awt.Dimension(202, 223));
        uuu.setOpaque(true);
        uuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uuuMouseClicked(evt);
            }
        });
        getContentPane().add(uuu);
        uuu.setBounds(0, 0, 480, 430);

        b.setMinimumSize(new java.awt.Dimension(20, 16));
        b.setPreferredSize(new java.awt.Dimension(7, 23));
        b.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bFocusGained(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(76, 80, 30, 23);

        c.setMinimumSize(new java.awt.Dimension(20, 16));
        c.setPreferredSize(new java.awt.Dimension(7, 23));
        c.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cFocusGained(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(106, 80, 30, 23);

        jLabel1.setBackground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("    1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 60, 30, 20);

        jLabel2.setBackground(new java.awt.Color(153, 255, 0));
        jLabel2.setText("    5");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(46, 80, 30, 20);

        d.setMinimumSize(new java.awt.Dimension(20, 16));
        d.setPreferredSize(new java.awt.Dimension(7, 23));
        d.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dFocusGained(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(156, 60, 30, 23);

        jLabel3.setBackground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("    6");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(156, 80, 30, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("    1");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(186, 80, 30, 20);

        jLabel5.setBackground(new java.awt.Color(153, 255, 0));
        jLabel5.setText("    2");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(216, 106, 30, 20);

        g.setMinimumSize(new java.awt.Dimension(20, 16));
        g.setPreferredSize(new java.awt.Dimension(7, 23));
        g.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                gFocusGained(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(216, 80, 30, 23);

        e.setMinimumSize(new java.awt.Dimension(20, 16));
        e.setPreferredSize(new java.awt.Dimension(7, 23));
        e.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                eFocusGained(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(186, 60, 30, 23);

        h.setMinimumSize(new java.awt.Dimension(20, 16));
        h.setPreferredSize(new java.awt.Dimension(7, 23));
        h.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                hFocusGained(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(46, 106, 30, 23);

        i.setMinimumSize(new java.awt.Dimension(20, 16));
        i.setPreferredSize(new java.awt.Dimension(7, 23));
        i.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                iFocusGained(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(76, 106, 30, 23);

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("    4");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(46, 126, 30, 20);

        j.setMinimumSize(new java.awt.Dimension(20, 16));
        j.setPreferredSize(new java.awt.Dimension(7, 23));
        j.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFocusGained(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(106, 106, 30, 23);

        l.setMinimumSize(new java.awt.Dimension(20, 16));
        l.setPreferredSize(new java.awt.Dimension(7, 23));
        l.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lFocusGained(evt);
            }
        });
        getContentPane().add(l);
        l.setBounds(106, 126, 30, 23);

        f.setMinimumSize(new java.awt.Dimension(20, 16));
        f.setPreferredSize(new java.awt.Dimension(7, 23));
        f.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fFocusGained(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(216, 60, 30, 23);

        m.setMinimumSize(new java.awt.Dimension(20, 16));
        m.setPreferredSize(new java.awt.Dimension(7, 23));
        m.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mFocusGained(evt);
            }
        });
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(156, 106, 30, 23);

        n.setMinimumSize(new java.awt.Dimension(7, 23));
        n.setPreferredSize(new java.awt.Dimension(7, 23));
        n.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nFocusGained(evt);
            }
        });
        getContentPane().add(n);
        n.setBounds(186, 106, 30, 23);

        o.setMinimumSize(new java.awt.Dimension(7, 23));
        o.setPreferredSize(new java.awt.Dimension(7, 23));
        o.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                oFocusGained(evt);
            }
        });
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });
        getContentPane().add(o);
        o.setBounds(156, 126, 30, 23);

        jLabel8.setBackground(new java.awt.Color(153, 255, 0));
        jLabel8.setText("    3");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(186, 126, 30, 20);

        jLabel10.setBackground(new java.awt.Color(153, 255, 0));
        jLabel10.setText("    4");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(76, 172, 30, 20);

        jLabel11.setBackground(new java.awt.Color(153, 255, 0));
        jLabel11.setText("    5");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(106, 172, 30, 20);

        r.setMinimumSize(new java.awt.Dimension(20, 16));
        r.setPreferredSize(new java.awt.Dimension(7, 23));
        r.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rFocusGained(evt);
            }
        });
        getContentPane().add(r);
        r.setBounds(76, 152, 30, 23);

        t.setMinimumSize(new java.awt.Dimension(20, 16));
        t.setPreferredSize(new java.awt.Dimension(7, 23));
        t.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tFocusGained(evt);
            }
        });
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(46, 172, 30, 23);

        s.setMinimumSize(new java.awt.Dimension(20, 16));
        s.setPreferredSize(new java.awt.Dimension(7, 23));
        s.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                sFocusGained(evt);
            }
        });
        getContentPane().add(s);
        s.setBounds(106, 152, 30, 23);

        q.setMinimumSize(new java.awt.Dimension(20, 16));
        q.setPreferredSize(new java.awt.Dimension(7, 23));
        q.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                qFocusGained(evt);
            }
        });
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });
        getContentPane().add(q);
        q.setBounds(46, 152, 30, 23);

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("    5");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(156, 152, 30, 20);

        jLabel13.setBackground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("    3");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13);
        jLabel13.setBounds(156, 172, 30, 20);

        v.setMinimumSize(new java.awt.Dimension(20, 16));
        v.setPreferredSize(new java.awt.Dimension(7, 23));
        v.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vFocusGained(evt);
            }
        });
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });
        getContentPane().add(v);
        v.setBounds(216, 172, 30, 23);

        u.setMinimumSize(new java.awt.Dimension(20, 16));
        u.setPreferredSize(new java.awt.Dimension(7, 23));
        u.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                uFocusGained(evt);
            }
        });
        getContentPane().add(u);
        u.setBounds(186, 172, 30, 23);

        jLabel14.setBackground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("    2");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(186, 152, 30, 20);

        jLabel15.setBackground(new java.awt.Color(153, 255, 0));
        jLabel15.setText("    3");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(106, 60, 30, 20);

        k.setMinimumSize(new java.awt.Dimension(20, 16));
        k.setPreferredSize(new java.awt.Dimension(7, 23));
        k.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                kFocusGained(evt);
            }
        });
        getContentPane().add(k);
        k.setBounds(76, 126, 30, 23);

        jLabel7.setBackground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("    4");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(216, 152, 30, 20);

        p.setMinimumSize(new java.awt.Dimension(7, 23));
        p.setPreferredSize(new java.awt.Dimension(7, 23));
        p.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pFocusGained(evt);
            }
        });
        getContentPane().add(p);
        p.setBounds(216, 126, 30, 23);

        Submit.setText("Submit");
        Submit.setMaximumSize(new java.awt.Dimension(70, 23));
        Submit.setMinimumSize(new java.awt.Dimension(70, 23));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(310, 100, 80, 23);

        a.setMinimumSize(new java.awt.Dimension(7, 23));
        a.setPreferredSize(new java.awt.Dimension(7, 23));
        a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                aFocusGained(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(76, 60, 32, 23);

        jButton1.setText("Reset");
        jButton1.setMaximumSize(new java.awt.Dimension(70, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(70, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 220, 61, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 280, 55, 23);

        yy.setText("jLabel9");
        getContentPane().add(yy);
        yy.setBounds(170, 240, 120, 50);

        jButton3.setText("End Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 160, 110, 23);

        jLabel9.setText("Time used");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 250, 60, 30);

        jLabel16.setFont(new java.awt.Font("Pristina", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 153));
        jLabel16.setText("Sudoku");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(90, 20, 150, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
tt.cancel();
        int A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U ,V;
A=Integer.parseInt(a.getText());
B=Integer.parseInt(b.getText());
C=Integer.parseInt(c.getText());
D=Integer.parseInt(d.getText());
E=Integer.parseInt(e.getText());
F=Integer.parseInt(f.getText());
G=Integer.parseInt(g.getText());        
H=Integer.parseInt(h.getText());
I=Integer.parseInt(i.getText());
J=Integer.parseInt(j.getText());
K=Integer.parseInt(k.getText());
L=Integer.parseInt(l.getText());
M=Integer.parseInt(m.getText());
N=Integer.parseInt(n.getText());
O=Integer.parseInt(o.getText());
P=Integer.parseInt(p.getText());
Q=Integer.parseInt(q.getText());
R=Integer.parseInt(r.getText());
S=Integer.parseInt(s.getText());
T=Integer.parseInt(t.getText());
U=Integer.parseInt(u.getText());
V=Integer.parseInt(v.getText());

if(A!=6)
         a.setBackground(Color.red);
     
if(B!=2)
    b.setBackground(Color.red);
      
if(C!=4)
    c.setBackground(Color.red);
    
if(D!=2)
    d.setBackground(Color.red);
   
if(E!=4)
    e.setBackground(Color.red);
      
if(F!=5)
    f.setBackground(Color.red);
    
if(G!=3)
    g.setBackground(Color.red);
      
if(H!=6)
    h.setBackground(Color.red);
     
if(I!=3)
    i.setBackground(Color.red);
    
if(J!=1)
    j.setBackground(Color.red);
     
if(K!=5)
    k.setBackground(Color.red);
    
if(L!=2)
    l.setBackground(Color.red);
      
if(M!=4)
   m.setBackground(Color.red);
    
if(N!=5)
    n.setBackground(Color.red);
     
if(O!=1)
    o.setBackground(Color.red);
      
if(P!=6)
    p.setBackground(Color.red);
    
if(Q!=3)
    q.setBackground(Color.red);
    
if(R!=1)
    r.setBackground(Color.red);
     
if(S!=6)
    s.setBackground(Color.red);
     
if(T!=2)
    t.setBackground(Color.red);
    
if(U!=6)
    u.setBackground(Color.red);
   if(V!=1)
v.setBackground(Color.red);
   
   if((A==6)&&(B==2)&&(C==4)&&(D==2)&&(E==4)&&(F==5)&&(G==3)&&(H==6)&&(I==3)&&(J==1)&&(K==5)&&(L==2)&&(M==4)&&(N==5)&&(O==1)&&(P==6)&&(Q==3)&&(R==1)&&(S==6)&&(T==2)&&(U==6)&&(V==1)){
                        JOptionPane.showMessageDialog(null,"Congratulations you have completed the game!!"); 
   
   try {
              Class.forName("java.sql.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","sarvani");
             Statement st = con.createStatement();
            int dd = Integer.parseInt(yy.getText());
             
             
            String q = ("insert into sudoku values("+"'"+"a"+"'"+","+dd+");");
          
              st.executeUpdate(q);
               st.close();
            con.close();
    }
       catch(Exception e) {
            System.out.print(e.getMessage());
       }
   
   {
   final String user="revrang2016@gmail.com";//change accordingly  
  final String password="*******";//change accordingly  
    
  String to="mailrrr@yahoo.in";//change accordingly  
  
   //Get the session object  
   Properties props = new Properties();  
   props.put("mail.smtp.host","smtp.gmail.com"); 
   props.put("mail.smtp.socketFactory.port", "465");
   props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
   props.put("mail.smtp.auth", "true");
   props.put("mail.smtp.port","465");
     
   Session session = Session.getDefaultInstance(props,  
    new javax.mail.Authenticator() {  
      protected PasswordAuthentication getPasswordAuthentication() {  
    return new PasswordAuthentication("revrang2016@gmail.com","********");  
      }  
    });  
  
   //Compose the message  
    try {  
     MimeMessage message = new MimeMessage(session);  
     message.setFrom(new InternetAddress("revrang2016@gmail.com"));  
     message.setRecipients(Message.RecipientType.TO,  InternetAddress.parse("mailrr@yahoo.in"));  
     message.setSubject("Email demo");  
     message.setText("This is simple program of sending email using JavaMail API");  
       
    //send the message  
     Transport.send(message);  
  
     System.out.println("message sent successfully...");  
   
     } catch (MessagingException e) {e.printStackTrace();}  
 }
   
      }                               
              
// TODO add your handling code here:
    }//GEN-LAST:event_SubmitActionPerformed

      
  

    private void aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aFocusGained
a.setBackground(Color.white);
        // TODO add your handling code here:
    }//GEN-LAST:event_aFocusGained

    private void dFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dFocusGained
      d.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_dFocusGained

    private void eFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_eFocusGained
       e.setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_eFocusGained

    private void fFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fFocusGained
       f .setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_fFocusGained

    private void bFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_bFocusGained
       b.setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_bFocusGained

    private void cFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cFocusGained
      c .setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_cFocusGained

    private void gFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_gFocusGained
       g .setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_gFocusGained

    private void hFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hFocusGained
        h.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_hFocusGained

    private void iFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iFocusGained
       f .setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_iFocusGained

    private void jFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFocusGained
      j .setBackground(Color.white); // TODO add your handling code here:
    }//GEN-LAST:event_jFocusGained

    private void mFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mFocusGained
        m.setBackground(Color.white);// TODO add your handling code here:
    }//GEN-LAST:event_mFocusGained

    private void nFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nFocusGained
              n .setBackground(Color.white);// TODO add your handling code here:
 // TODO add your handling code here:
    }//GEN-LAST:event_nFocusGained

    private void kFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_kFocusGained
              k  .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_kFocusGained

    private void lFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lFocusGained
              l .setBackground(Color.white);// TODO add your handling code here:
 // TODO add your handling code here:
    }//GEN-LAST:event_lFocusGained

    private void oFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oFocusGained
               o .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_oFocusGained

    private void pFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pFocusGained
               p .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_pFocusGained

    private void qFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qFocusGained
                q.setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_qFocusGained

    private void rFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rFocusGained
                r.setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_rFocusGained

    private void sFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sFocusGained
               s .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_sFocusGained

    private void tFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tFocusGained
               t .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_tFocusGained

    private void uFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_uFocusGained
               u .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_uFocusGained

    private void vFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vFocusGained
               v .setBackground(Color.white);// TODO add your handling code here:
// TODO add your handling code here:
    }//GEN-LAST:event_vFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      tt.cancel();
      Timer tt=new Timer();
      tt.scheduleAtFixedRate(new TimerTask(){
int a=0;
            @Override
            public void run() {
                a++;
                yy.setText(""+a);
                
            }
            
        },0,1000);
        
        a.setText("");
        b.setText("");
        c.setText("");
        d.setText("");
        e.setText("");
        f.setText("");
        g.setText("");
        h.setText("");
        i.setText("");
        j.setText("");
        k.setText("");
        l.setText("");
        m.setText("");
        n.setText("");
        o.setText("");
        p.setText("");
        q.setText("");
        r.setText("");
        t.setText("");
        s.setText("");
        v.setText("");
        
        a.setBackground(Color.white);
        b.setBackground(Color.white);
        c.setBackground(Color.white);
        d.setBackground(Color.white);
        e.setBackground(Color.white);
        f.setBackground(Color.white);
        g.setBackground(Color.white);
        h.setBackground(Color.white);
        i.setBackground(Color.white);
        j.setBackground(Color.white);
        k.setBackground(Color.white);
        l.setBackground(Color.white);
        m.setBackground(Color.white);
        n.setBackground(Color.white);
        o.setBackground(Color.white);
        p.setBackground(Color.white);
        q.setBackground(Color.white);
        r.setBackground(Color.white);
        s.setBackground(Color.white);
        t.setBackground(Color.white);
        u.setBackground(Color.white);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void uuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uuuMouseClicked
uuu.setVisible(false);
tt.scheduleAtFixedRate(new TimerTask(){
int a=0;
            @Override
            public void run() {
                a++;
                yy.setText(""+a);
                
            }
            
        },0,1000);
        // TODO add your handling code here:
    }//GEN-LAST:event_uuuMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Recreation Obj= new Recreation();
        Obj.setVisible(true);
        Sudoku6_1.this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
tt.cancel();
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sudoku6_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sudoku6_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sudoku6_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sudoku6_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sudoku6_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField c;
    private javax.swing.JTextField d;
    private javax.swing.JTextField e;
    private javax.swing.JTextField f;
    private javax.swing.JTextField g;
    private javax.swing.JTextField h;
    private javax.swing.JTextField i;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField k;
    private javax.swing.JTextField l;
    private javax.swing.JTextField m;
    private javax.swing.JTextField n;
    private javax.swing.JTextField o;
    private javax.swing.JTextField p;
    private javax.swing.JTextField q;
    private javax.swing.JTextField r;
    private javax.swing.JTextField s;
    private javax.swing.JTextField t;
    private javax.swing.JTextField u;
    private javax.swing.JLabel uuu;
    private javax.swing.JTextField v;
    private javax.swing.JLabel yy;
    // End of variables declaration//GEN-END:variables
}
