import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class TICTACTOE1 extends javax.swing.JFrame {
   class gg{
}
class tic{
       void cc() {try {
              Class.forName("java.sql.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost/ipproject","root","sarvani");
             Statement st = con.createStatement();
            String dd=JOptionPane.showInputDialog(null,"Winner, please enter your name.");
                          
            String q = ("insert into tictactoe values("+"'"+dd+"'"+");");
          
              st.executeUpdate(q);
              
    }
       catch(Exception e) {
            System.out.print(e.getMessage());
       }
       {}
       
       }
    
    String z =a.getText();
String y =b.getText();
String x =c.getText();
String w =d.getText();
String v =e.getText();
String u =f.getText();
String t =g.getText();
String s =h.getText();
String r =i.getText();
void show()
{
    if(("".equals(a.getText()))||("".equals(b.getText()))||("".equals(c.getText()))||("".equals(d.getText()))||("".equals(e.getText()))||("".equals(f.getText()))||("".equals(g.getText()))||("".equals(h.getText()))||("".equals(i.getText())))
    System.out.println("");
 if ((z.equals(y)&&z.equals(x))&&(z!="")){
    JOptionPane.showMessageDialog(null,z+" Won");
 cc();}
else if ((z.equals(w)&&z.equals(t))&&(z!="")){
    JOptionPane.showMessageDialog(null,z+" Won");cc();}
else if ((z.equals(v)&&z.equals(r))&&(z!="")){
    JOptionPane.showMessageDialog(null,z+" Won");cc();}
else if ((w.equals(v)&&w.equals(u))&&(w!="")){
    JOptionPane.showMessageDialog(null,x+" Won");cc();}
else if ((t.equals(s)&&t.equals(r))&&(t!="")){
    JOptionPane.showMessageDialog(null,t+" Won");cc();}
else if ((x.equals(u)&&x.equals(r))&&(x!="")){
    JOptionPane.showMessageDialog(null,x+" Won");cc();}
else if ((y.equals(v)&&y.equals(s))&&(y!="")){
    JOptionPane.showMessageDialog(null,y+" Won");cc();}
else if ((x.equals(v)&&x.equals(t))&&(x!="")){
    JOptionPane.showMessageDialog(null,x+" Won");cc();}
if((""!=(a.getText()))&&(""!=(b.getText()))&&(""!=(c.getText()))&&(""!=(d.getText()))&&(""!=(e.getText()))&&(""!=(f.getText()))&&(""!=(g.getText()))&&(""!=(h.getText()))&&(""!=(i.getText())))
 JOptionPane.showMessageDialog(null,"Draw");
}
}
    /**
     * Creates new form TICTACTOE1
     */
    public TICTACTOE1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ll = new javax.swing.JLabel();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(268, 306));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        ll.setBackground(new java.awt.Color(153, 153, 255));
        ll.setFont(new java.awt.Font("Pristina", 0, 18)); // NOI18N
        ll.setText("<HTml><center>RULES</center><br>Players alternate placing Xs and Os on the grid until either (a) one player has three in a row, horizontally, vertically or diagonally; or (b) all nine squares are filled. If a player is able to draw three Xs or three Os in a row, that player wins. If all nine squares are filled and neither player has three in a row, the game is a draw.<center>Click to Start</center></html>");
        ll.setOpaque(true);
        ll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llMouseClicked(evt);
            }
        });
        getContentPane().add(ll);
        ll.setBounds(0, 0, 260, 280);

        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(39, 74, 45, 27);

        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(90, 74, 46, 27);

        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(143, 74, 44, 28);

        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(39, 111, 45, 27);

        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(90, 111, 46, 27);

        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(143, 111, 44, 27);

        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(39, 149, 45, 27);

        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(90, 149, 46, 27);

        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(143, 149, 44, 27);

        jButton10.setText("New Game");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(25, 194, 100, 23);

        jButton13.setText("Back");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(143, 194, 55, 23);

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        jLabel1.setText("TIC TAC TOE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 11, 156, 45);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(87, 235, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents
int count=0;

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
 if(count%2==0)
a.setText("X");
 else 
a.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:
    }//GEN-LAST:event_aActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
 if(count%2==0)
b.setText("X");
 else 
b.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:     // TODO add your handling code here:
    }//GEN-LAST:event_bActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
 if(count%2==0)
c.setText("X");
 else 
c.setText("O");
 count++;
 tic obj=new tic();
   obj.show();
    // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
 if(count%2==0)
d.setText("X");
 else 
d.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:      // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
 if(count%2==0)
e.setText("X");
 else 
e.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:     // TODO add your handling code here:
    }//GEN-LAST:event_eActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
 if(count%2==0)
f.setText("X");
 else 
f.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:     // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
 if(count%2==0)
g.setText("X");
 else 
g.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
 if(count%2==0)
h.setText("X");
 else 
h.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

// TODO add your handling code here:      // TODO add your handling code here:
    }//GEN-LAST:event_hActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
 if(count%2==0)
i.setText("X");
 else 
i.setText("O");
 count++;
 tic obj=new tic();
   obj.show();

   // TODO add your handling code here:
    }//GEN-LAST:event_iActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
a.setText("");  
b.setText("");
c.setText("");
d.setText("");
e.setText("");
f.setText("");
g.setText("");
h.setText("");
i.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
Recreation Obj=new Recreation();
   Obj.setVisible(true);
TICTACTOE1.this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
getContentPane().setBackground(Color.YELLOW);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void llMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llMouseClicked
ll.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_llMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TICTACTOE1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TICTACTOE1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton i;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel ll;
    // End of variables declaration//GEN-END:variables
}
